import type { ClinicData } from "@/types/clinic";

export const CAMBRIDGE_SEED_CLINICS: ClinicData[] = [
  {
    id: "bourn-hall",
    name: "Bourn Hall Clinic",
    address: "Bourn, Cambridge, CB23 2TN",
    phone: "01954 717 400",
    website: "https://www.bournhall.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0001",
    soloFriendly: true,
    distanceMiles: 9,
    prices: {
      basicIvf: 4500,
      ivfIcsi: 5200,
      donorSpermIvf: 5500,
      donorEggIvf: 8500,
      embryoStorage: 350,
      soloPackage: 5800,
      consultation: 200,
    },
    packages: [
      {
        name: "2-Cycle IVF Package",
        price: 8200,
        saves: 800,
        description: "Two full IVF cycles with shared monitoring costs. Unused cycle refunded if pregnancy achieved on first.",
      },
      {
        name: "3-Cycle IVF Package",
        price: 11500,
        saves: 2000,
        description: "Three IVF cycles — most popular option for solo patients. Includes priority booking and a dedicated nurse coordinator.",
      },
      {
        name: "3-Cycle Donor Sperm IVF",
        price: 13800,
        saves: 2700,
        description: "Three cycles with donor sperm included. Covers sperm preparation and ICSI in each cycle.",
      },
      {
        name: "IVF + Freeze All Package",
        price: 6200,
        saves: 300,
        description: "Single IVF cycle with all eligible embryos frozen for future frozen embryo transfers (FETs).",
      },
    ],
    successRates: {
      under35: 44,
      age35to37: 36,
      age38to39: 25,
      age40to42: 14,
      age43plus: 5,
    },
    waitingTimeWeeks: 4,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "care-cambridge",
    name: "CARE Fertility Cambridge",
    address: "Nuffield Road, Cambridge, CB4 1GL",
    phone: "01223 349 244",
    website: "https://www.carefertility.com/fertility-clinics/cambridge",
    hfeaLicensed: true,
    hfeaNumber: "0046",
    soloFriendly: true,
    distanceMiles: 2,
    prices: {
      basicIvf: 4200,
      ivfIcsi: 5000,
      donorSpermIvf: 5200,
      donorEggIvf: 8200,
      embryoStorage: 300,
      soloPackage: 5400,
      consultation: 175,
    },
    packages: [
      {
        name: "2-Cycle IVF Package",
        price: 7800,
        saves: 600,
        description: "Two IVF cycles with ICSI included. Shared nurse support and one fertility counselling session.",
      },
      {
        name: "3-Cycle IVF Package",
        price: 10800,
        saves: 1800,
        description: "Three cycles at a fixed price. Includes embryoscope time-lapse monitoring throughout.",
      },
      {
        name: "2-Cycle Donor Sperm IVF",
        price: 9600,
        saves: 800,
        description: "Two cycles with donor sperm handling, sperm prep, and ICSI in each cycle.",
      },
      {
        name: "CAREmaps Genetic Testing Bundle",
        price: 7200,
        description: "Single IVF cycle with PGT-A (preimplantation genetic testing) for all retrieved embryos. HFEA amber-rated add-on.",
      },
    ],
    successRates: {
      under35: 40,
      age35to37: 33,
      age38to39: 22,
      age40to42: 12,
      age43plus: 4,
    },
    waitingTimeWeeks: 6,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "herts-essex",
    name: "Herts & Essex Fertility Centre",
    address: "Bishops' College, Churchgate, Cheshunt, EN8 9XQ",
    phone: "01992 78 50 60",
    website: "https://www.hertsandessexfertility.com",
    hfeaLicensed: true,
    hfeaNumber: "0093",
    soloFriendly: true,
    distanceMiles: 28,
    prices: {
      basicIvf: 3950,
      ivfIcsi: 4750,
      donorSpermIvf: 5100,
      donorEggIvf: 7800,
      embryoStorage: 280,
      consultation: 150,
    },
    packages: [
      {
        name: "2-Cycle IVF Package",
        price: 7200,
        saves: 700,
        description: "Two cycles with ICSI and extended embryo culture. One fertility counselling session included.",
      },
      {
        name: "3-Cycle IVF Package",
        price: 9900,
        saves: 1950,
        description: "Best value across three cycles. Includes embryo glue and assisted hatching on final cycle.",
      },
      {
        name: "Donor Sperm 2-Cycle Package",
        price: 9000,
        saves: 1200,
        description: "Two full cycles with donor sperm import, preparation, and ICSI included.",
      },
    ],
    successRates: {
      under35: 38,
      age35to37: 30,
      age38to39: 20,
      age40to42: 11,
      age43plus: 3,
    },
    waitingTimeWeeks: 8,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "london-womens-clinic",
    name: "London Women's Clinic",
    address: "113–115 Harley Street, London, W1G 6AP",
    phone: "020 7563 4309",
    website: "https://www.londonwomensclinic.com",
    hfeaLicensed: true,
    hfeaNumber: "0006",
    soloFriendly: true,
    distanceMiles: 55,
    prices: {
      basicIvf: 4800,
      ivfIcsi: 5600,
      donorSpermIvf: 5900,
      donorEggIvf: 9200,
      embryoStorage: 400,
      soloPackage: 6200,
      consultation: 250,
    },
    packages: [
      {
        name: "Solo Patient 2-Cycle Package",
        price: 10800,
        saves: 1000,
        description: "Designed specifically for solo patients — two cycles with donor sperm co-ordination, ICSI, and a solo-focused counselling session.",
      },
      {
        name: "3-Cycle IVF Package",
        price: 14800,
        saves: 2600,
        description: "Three full IVF cycles with ICSI. Priority scheduling and one-to-one nurse support throughout.",
      },
      {
        name: "Donor Egg IVF Package",
        price: 12500,
        saves: 1700,
        description: "Two donor egg IVF cycles from the clinic's own egg bank. Includes recipient medication and embryo transfer.",
      },
      {
        name: "IVF + PGT-A Bundle",
        price: 8200,
        description: "Single cycle with full preimplantation genetic testing. Recommended for patients 38+ or with previous implantation failure.",
      },
    ],
    successRates: {
      under35: 45,
      age35to37: 37,
      age38to39: 26,
      age40to42: 15,
      age43plus: 5,
    },
    waitingTimeWeeks: 3,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "create-fertility",
    name: "Create Fertility",
    address: "150 Cheapside, London, EC2V 6ET",
    phone: "0333 202 0475",
    website: "https://www.createfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0152",
    soloFriendly: true,
    distanceMiles: 58,
    prices: {
      basicIvf: 3500,
      ivfIcsi: 4300,
      donorSpermIvf: 4800,
      donorEggIvf: 7500,
      embryoStorage: 250,
      soloPackage: 5000,
      consultation: 150,
    },
    packages: [
      {
        name: "2-Cycle Natural/Mild IVF",
        price: 6200,
        saves: 800,
        description: "Create's signature mild-stimulation approach — lower drug costs, gentler on the body. Two cycles at a reduced combined rate.",
      },
      {
        name: "3-Cycle Mild IVF Package",
        price: 8700,
        saves: 1800,
        description: "Three mild IVF cycles. Create specialise in natural and mild protocols — lower drug spend means total cost is often lower than standard IVF elsewhere.",
      },
      {
        name: "2-Cycle Donor Sperm Package",
        price: 8800,
        saves: 800,
        description: "Two cycles with donor sperm processing and ICSI. Open-ID donors available from multiple banks.",
      },
      {
        name: "Freeze & 2 FET Package",
        price: 5500,
        description: "One stimulated IVF cycle with freeze-all, plus two subsequent frozen embryo transfers. Ideal for banking embryos before starting transfers.",
      },
    ],
    successRates: {
      under35: 36,
      age35to37: 28,
      age38to39: 19,
      age40to42: 10,
      age43plus: 3,
    },
    waitingTimeWeeks: 2,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "lister-fertility",
    name: "Lister Fertility Clinic",
    address: "Chelsea Bridge Road, London, SW1W 8RH",
    phone: "020 7881 9001",
    website: "https://www.listerfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0012",
    soloFriendly: true,
    distanceMiles: 60,
    prices: {
      basicIvf: 5200,
      ivfIcsi: 6100,
      donorSpermIvf: 6400,
      donorEggIvf: 9800,
      embryoStorage: 450,
      consultation: 300,
    },
    packages: [
      {
        name: "IVF + Endometrial Receptivity Package",
        price: 7800,
        description: "IVF cycle with ERA (Endometrial Receptivity Analysis) test. Recommended after one or more failed transfers in patients with a good embryo.",
      },
      {
        name: "2-Cycle IVF Package",
        price: 9800,
        saves: 600,
        description: "Two IVF cycles with ICSI. Lister does not offer discounted multi-cycle bundles widely, but this package is available on request.",
      },
      {
        name: "Donor Egg IVF (own donor)",
        price: 11500,
        description: "Complete donor egg cycle using a known or clinic-matched donor. Includes all recipient preparation, transfer, and medication.",
      },
    ],
    successRates: {
      under35: 48,
      age35to37: 40,
      age38to39: 28,
      age40to42: 17,
      age43plus: 6,
    },
    waitingTimeWeeks: 4,
    nhsReferrals: false,
    paymentPlans: false,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "kings-fertility",
    name: "King's Fertility",
    address: "Denmark Hill, London, SE5 9RS",
    phone: "020 3299 3637",
    website: "https://www.kingsfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0180",
    soloFriendly: false,
    distanceMiles: 62,
    prices: {
      basicIvf: 4100,
      ivfIcsi: 4900,
      donorSpermIvf: 5100,
      donorEggIvf: 7900,
      embryoStorage: 320,
      consultation: 200,
    },
    packages: [
      {
        name: "2-Cycle IVF Package",
        price: 7400,
        saves: 800,
        description: "Two IVF cycles with ICSI. King's is primarily an NHS-linked unit; private packages have limited availability.",
      },
      {
        name: "IVF + FET Package",
        price: 5900,
        saves: 200,
        description: "One fresh IVF cycle plus one frozen embryo transfer, at a combined price.",
      },
    ],
    successRates: {
      under35: 39,
      age35to37: 31,
      age38to39: 21,
      age40to42: 11,
      age43plus: 3,
    },
    waitingTimeWeeks: 10,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "addenbrookes",
    name: "Addenbrooke's Assisted Conception Unit",
    address: "Cambridge University Hospitals, Hills Road, CB2 0QQ",
    phone: "01223 216 859",
    website: "https://www.cuh.nhs.uk/our-services/assisted-conception-unit",
    hfeaLicensed: true,
    hfeaNumber: "0042",
    soloFriendly: false,
    distanceMiles: 2,
    prices: {
      basicIvf: 3800,
      ivfIcsi: 4600,
      donorSpermIvf: 4900,
      embryoStorage: 300,
      consultation: 0,
    },
    packages: [
      {
        name: "NHS-funded IVF (if eligible)",
        price: 0,
        description: "Addenbrooke's offers NHS-funded treatment for eligible patients. Single women may qualify — check current Cambridgeshire ICB criteria before self-funding.",
      },
    ],
    successRates: {
      under35: 37,
      age35to37: 29,
      age38to39: 18,
      age40to42: 9,
      age43plus: 2,
    },
    waitingTimeWeeks: 16,
    nhsReferrals: true,
    paymentPlans: false,
    fetchedAt: new Date().toISOString(),
  },
];
