import type { ClinicData } from "@/types/clinic";

export const CAMBRIDGE_SEED_CLINICS: ClinicData[] = [
  {
    id: "bourn-hall",
    name: "Bourn Hall Clinic",
    address: "Bourn, Cambridge, CB23 2TN",
    phone: "01954 717 400",
    website: "https://www.bournhall.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0001",
    soloFriendly: true,
    distanceMiles: 9,
    prices: {
      basicIvf: 4500,
      ivfIcsi: 5200,
      donorSpermIvf: 5500,
      donorEggIvf: 8500,
      embryoStorage: 350,
      soloPackage: 5800,
      consultation: 200,
    },
    successRates: {
      under35: 44,
      age35to37: 36,
      age38to39: 25,
    },
    waitingTimeWeeks: 4,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "care-cambridge",
    name: "CARE Fertility Cambridge",
    address: "Nuffield Road, Cambridge, CB4 1GL",
    phone: "01223 349 244",
    website: "https://www.carefertility.com/fertility-clinics/cambridge",
    hfeaLicensed: true,
    hfeaNumber: "0046",
    soloFriendly: true,
    distanceMiles: 2,
    prices: {
      basicIvf: 4200,
      ivfIcsi: 5000,
      donorSpermIvf: 5200,
      donorEggIvf: 8200,
      embryoStorage: 300,
      soloPackage: 5400,
      consultation: 175,
    },
    successRates: {
      under35: 40,
      age35to37: 33,
      age38to39: 22,
    },
    waitingTimeWeeks: 6,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "herts-essex",
    name: "Herts & Essex Fertility Centre",
    address: "Bishops' College, Churchgate, Cheshunt, EN8 9XQ",
    phone: "01992 78 50 60",
    website: "https://www.hertsandessexfertility.com",
    hfeaLicensed: true,
    hfeaNumber: "0093",
    soloFriendly: true,
    distanceMiles: 28,
    prices: {
      basicIvf: 3950,
      ivfIcsi: 4750,
      donorSpermIvf: 5100,
      donorEggIvf: 7800,
      embryoStorage: 280,
      consultation: 150,
    },
    successRates: {
      under35: 38,
      age35to37: 30,
      age38to39: 20,
    },
    waitingTimeWeeks: 8,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "london-womens-clinic",
    name: "London Women's Clinic",
    address: "113–115 Harley Street, London, W1G 6AP",
    phone: "020 7563 4309",
    website: "https://www.londonwomensclinic.com",
    hfeaLicensed: true,
    hfeaNumber: "0006",
    soloFriendly: true,
    distanceMiles: 55,
    prices: {
      basicIvf: 4800,
      ivfIcsi: 5600,
      donorSpermIvf: 5900,
      donorEggIvf: 9200,
      embryoStorage: 400,
      soloPackage: 6200,
      consultation: 250,
    },
    successRates: {
      under35: 45,
      age35to37: 37,
      age38to39: 26,
    },
    waitingTimeWeeks: 3,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "create-fertility",
    name: "Create Fertility",
    address: "150 Cheapside, London, EC2V 6ET",
    phone: "0333 202 0475",
    website: "https://www.createfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0152",
    soloFriendly: true,
    distanceMiles: 58,
    prices: {
      basicIvf: 3500,
      ivfIcsi: 4300,
      donorSpermIvf: 4800,
      donorEggIvf: 7500,
      embryoStorage: 250,
      soloPackage: 5000,
      consultation: 150,
    },
    successRates: {
      under35: 36,
      age35to37: 28,
      age38to39: 19,
    },
    waitingTimeWeeks: 2,
    nhsReferrals: false,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "lister-fertility",
    name: "Lister Fertility Clinic",
    address: "Chelsea Bridge Road, London, SW1W 8RH",
    phone: "020 7881 9001",
    website: "https://www.listerfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0012",
    soloFriendly: true,
    distanceMiles: 60,
    prices: {
      basicIvf: 5200,
      ivfIcsi: 6100,
      donorSpermIvf: 6400,
      donorEggIvf: 9800,
      embryoStorage: 450,
      consultation: 300,
    },
    successRates: {
      under35: 48,
      age35to37: 40,
      age38to39: 28,
    },
    waitingTimeWeeks: 4,
    nhsReferrals: false,
    paymentPlans: false,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "kings-fertility",
    name: "King's Fertility",
    address: "Denmark Hill, London, SE5 9RS",
    phone: "020 3299 3637",
    website: "https://www.kingsfertility.co.uk",
    hfeaLicensed: true,
    hfeaNumber: "0180",
    soloFriendly: false,
    distanceMiles: 62,
    prices: {
      basicIvf: 4100,
      ivfIcsi: 4900,
      donorSpermIvf: 5100,
      donorEggIvf: 7900,
      embryoStorage: 320,
      consultation: 200,
    },
    successRates: {
      under35: 39,
      age35to37: 31,
      age38to39: 21,
    },
    waitingTimeWeeks: 10,
    nhsReferrals: true,
    paymentPlans: true,
    fetchedAt: new Date().toISOString(),
  },
  {
    id: "addenbrookes",
    name: "Addenbrooke's Assisted Conception Unit",
    address: "Cambridge University Hospitals, Hills Road, CB2 0QQ",
    phone: "01223 216 859",
    website: "https://www.cuh.nhs.uk/our-services/assisted-conception-unit",
    hfeaLicensed: true,
    hfeaNumber: "0042",
    soloFriendly: false,
    distanceMiles: 2,
    prices: {
      basicIvf: 3800,
      ivfIcsi: 4600,
      donorSpermIvf: 4900,
      embryoStorage: 300,
      consultation: 0,
    },
    successRates: {
      under35: 37,
      age35to37: 29,
      age38to39: 18,
    },
    waitingTimeWeeks: 16,
    nhsReferrals: true,
    paymentPlans: false,
    fetchedAt: new Date().toISOString(),
  },
];
